### ISSUE TITLE
IsRecordType fails with a NPE if the record type no longer exists

### ISSUE THREAD

**Issue by paulknebulaconsulting** [Nebula-Consulting/nebula-core#48]
https://github.com/Nebula-Consulting/nebula-core/blob/b5667dc42907d893a5882c8cbdba3dedec468d22/force-app/lazyIterator/classes/IsRecordType.cls#L18

Whilst I think this is normally fine, if the record type is removed, triggers will fail until they are corrected or the Record Type reinstated.

Would it be better to return a false in these instances instead of throwing the exception?

To replicate:
```
new nebc.IsRecordType(Opportunity.SObjectType, 'Test');
```

```
15:19:06.311 (408441414)|EXCEPTION_THROWN|[18]|System.NullPointerException: Attempt to de-reference a null object
15:19:06.311 (408550296)|SYSTEM_MODE_EXIT|false
15:19:06.311 (408664539)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

Class.nebc.IsRecordType.<init>: line 18, column 1
AnonymousBlock: line 1, column 1
AnonymousBlock: line 1, column 1
```

**Comment by paulknebulaconsulting** [comment]
@DanBeerNebula Wanted to get your thoughts on this.

**Comment by DanBeerNebula** [comment]
@paulknebulaconsulting from a purist point of view it should return false if the record type doesn't exist.

But in your example, I would want it to fail and fail hard - so we can see this and act accordingly.

If the record type is deleted then is this code still required? If the name has changed, do we update the code to the new name?

Ideally, all changes should be made in a Sandbox first - so we can see the errors upfront - but I know this isn't always the case and why we'd want to allow the system to continue...

**Comment by paulknebulaconsulting** [comment]
The org needs to be corrected to support the change, that's the better change. Thanks, I'll close this.
